### ISSUE TITLE
[DOCS] Project TODOs

### ISSUE THREAD

**Issue by Maxelweb** [Maxelweb/FuzzQR#1]
> Try to hack the QRCode library or try to hack operations before the sign checking

- [x] Analysis on QR Code Literature (#2 #6)
- [x] General analysis on VerificaC19 app (on Android) (#5)
- [x] Script creation to generate malevolous QR codes (#7 #4)
